// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igwpiwzexabejsdcvpnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlnd3Bpd3pleGFiZWpzZGN2cG5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzODQyNzAsImV4cCI6MjA1MDk2MDI3MH0.GEWrUEt_TOG_oebRfMQGMjoK3HANG3ue6AYe3JBpdC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);